---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: prowlarr
  namespace: cnpg
spec:
  name: prowlarr
  owner: prowlarr
  cluster:
    name: home

---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: prowlarr-logs
  namespace: cnpg
spec:
  name: prowlarr-logs
  owner: prowlarr
  cluster:
    name: home

---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: prowlarr
  namespace: cnpg
spec:
  cluster:
    name: home
  name: prowlarr
  login: true
  superuser: false
  createdb: true
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: useraccount-prowlarr