---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets-prowlarr
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets-prowlarr
  dataFrom:
  - extract:
      key: /prowlarr

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: useraccount-prowlarr
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: useraccount-prowlarr
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: /database/prowlarr
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
