---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden
  namespace: cnpg
spec:
  name: vaultwarden
  owner: vaultwarden
  cluster:
    name: home

---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: vaultwarden
  namespace: cnpg
spec:
  cluster:
    name: home
  name: vaultwarden
  login: true
  superuser: false
  createdb: true
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: useraccount-vaultwarden