apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: k8s-cloud
spec:
  newTunnel:
    name: k8s-cloud
  size: 2
  cloudflare:
    domain: REPLACE_ME.example.com
    accountName: REPLACE_ME
    email: ken.lasko@gmail.com
    secret: cloudflare-operator-secrets
