---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: homeassist
  namespace: cnpg
spec:
  name: homeassist
  owner: homeassist
  cluster:
    name: home

---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: homeassist
  namespace: cnpg
spec:
  cluster:
    name: home
  name: homeassist
  login: true
  superuser: false
  createdb: true
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: useraccount-homeassist