---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-operator-secrets
  namespace: cloudflare-operator
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: cloudflare-operator-secrets
  data:
  - secretKey: CLOUDFLARE_API_TOKEN
    remoteRef:
      key: /cloudflare/operator-api-token
