---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-operator-secret
  namespace: cloudflare-operator
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: operator-api-token
  data:
  - secretKey: token 
    remoteRef:
      key: /cloudflare/operator-api-token