---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-secrets
  namespace: kube-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: kite-secrets
    template:
      engineVersion: v2
      data:
        KITE_USERNAME: "{{ .kiteUsername }}"
        KITE_PASSWORD: "{{ .kitePassword }}"
        KITE_ENCRYPT_KEY: "{{ .kiteEncryptKey }}"
        KITE_JWT_SECRET: "{{ .kiteJWTSecret }}"
        KITE_OAUTH_CLIENT_ID: "{{ .kiteOauthClientId }}"
        KITE_OAUTH_CLIENT_SECRET: "{{ .kiteOauthClientSecret }}"
        DB_TYPE: "postgres"
        DB_DSN: "host=home-rw.cnpg.svc.cluster.local port=5432 user={{ .dbUsername }} password={{ .dbPassword }} dbname=kite"
        KITE_KUBECONFIG_CLOUD: "{{ .kiteKubeConfigCloud }}"
  data:
  - secretKey: kiteUsername
    remoteRef:
      key: /kite/secrets
      property: KITE_USERNAME
  - secretKey: kitePassword
    remoteRef:
      key: /kite/secrets
      property: KITE_PASSWORD
  - secretKey: kiteEncryptKey
    remoteRef:
      key: /kite/secrets
      property: KITE_ENCRYPT_KEY
  - secretKey: kiteJWTSecret
    remoteRef:
      key: /kite/secrets
      property: KITE_JWT_SECRET
  - secretKey: kiteOauthClientId
    remoteRef:
      key: /kite/secrets
      property: KITE_OAUTH_CLIENT_ID
  - secretKey: kiteOauthClientSecret
    remoteRef:
      key: /kite/secrets
      property: KITE_OAUTH_CLIENT_SECRET
  - secretKey: dbUsername
    remoteRef:
      key: /database/kite
      property: username
  - secretKey: dbPassword
    remoteRef:
      key: /database/kite
      property: password
  - secretKey: kiteKubeConfigCloud
    remoteRef:
      key: /kite/secrets
      property: KITE_KUBECONFIG_CLOUD
      decodingStrategy: Base64

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-cluster-config
  namespace: kube-system
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: kubeconfig-cloud
  data:
  - secretKey: kubeconfig-cloud
    remoteRef:
      key: /kite/kubeconfig-cloud
      decodingStrategy: Base64
