---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-dns-secret
  namespace: external-dns
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: unifi-dns-secret
  dataFrom:
  - extract:
      key: /external-dns-unifi-webhook
