apiVersion: networking.cfargotunnel.com/v1alpha1
kind: ClusterTunnel
metadata:
  name: k8s-home
spec:
  newTunnel:
    name: k8s-home
  cloudflare:
    domain: laskonet.com
    email: ken.lasko@gmail.com
    secret: cloudflare-operator-secret
    accountId: fa831d805d821b7c4627b464a9845a9d
