nameOverride: adguard-logcentral
image:
  repository: kenlasko/adguard-logcentral
  tag: latest
  registry: ghcr.io
priorityClassName: medium-priority
securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop: ["ALL"]
resources:
  requests:
    cpu: 1m
    memory: 25Mi
  limits:
    # cpu: 60m
    memory: 60Mi
envFrom:
- secretRef:
    name: adguard-logcentral-secrets
env:
- name: OIDC_ISSUER_URL
  value: https://auth.laskonet.com
- name: OIDC_REDIRECT_URL
  value: https://adguard-logcentral.laskonet.com/auth/callback
- name: ADGUARD_1_URL
  value: "http://adguard-service:3000"
- name: ADGUARD_1_USERNAME
  valueFrom:
    secretKeyRef:
      name: adguard-logcentral-secrets
      key: username
- name: ADGUARD_1_PASSWORD
  valueFrom:
    secretKeyRef:
      name: adguard-logcentral-secrets
      key: password
- name: ADGUARD_2_URL
  value: "https://adguard-rpi1.laskonet.com"
- name: ADGUARD_2_USERNAME
  valueFrom:
    secretKeyRef:
      name: adguard-logcentral-secrets
      key: username
- name: ADGUARD_2_PASSWORD
  valueFrom:
    secretKeyRef:
      name: adguard-logcentral-secrets
      key: password
- name: ADGUARD_3_URL
  value: "https://adguard-rpi2.laskonet.com"
- name: ADGUARD_3_USERNAME
  valueFrom:
    secretKeyRef:
      name: adguard-logcentral-secrets
      key: username
- name: ADGUARD_3_PASSWORD
  valueFrom:
    secretKeyRef:
      name: adguard-logcentral-secrets
      key: password
- name: ADGUARD_4_URL
  value: "http://cloud-adguard-link.tailscale.svc.cluster.local:3000"
- name: ADGUARD_4_USERNAME
  valueFrom:
    secretKeyRef:
      name: adguard-logcentral-secrets
      key: username
- name: ADGUARD_4_PASSWORD
  valueFrom:
    secretKeyRef:
      name: adguard-logcentral-secrets
      key: password
readinessProbe:
  httpGet: { path: /healthz, port: 8080 }
livenessProbe:
  httpGet: { path: /healthz, port: 8080 }
service:
  port: 8080