---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: seerr
  namespace: cnpg
spec:
  name: seerr
  owner: seerr
  cluster:
    name: home

---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: seerr
  namespace: cnpg
spec:
  cluster:
    name: home
  name: seerr
  login: true
  superuser: false
  createdb: true
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: useraccount-seerr