---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seerr-secrets
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: seerr-secrets
  data:
  - secretKey: DB_USER
    remoteRef:
      key: /database/seerr
      property: username
  - secretKey: DB_PASS
    remoteRef:
      key: /database/seerr
      property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: useraccount-seerr
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: useraccount-seerr
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: /database/seerr
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
