---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets-bazarr
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets-bazarr
  data:
  - secretKey: POSTGRES_USERNAME
    remoteRef:
      key: /database/bazarr
      property: username
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: /database/bazarr
      property: password

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: useraccount-bazarr
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: useraccount-bazarr
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: /database/bazarr
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
