---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: monize
  namespace: cnpg
spec:
  name: monize
  owner: monize
  cluster:
    name: home

---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: monize
  namespace: cnpg
spec:
  cluster:
    name: home
  name: monize
  login: true
  superuser: false
  createdb: true
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: useraccount-monize

---
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: monize-app
  namespace: cnpg
spec:
  cluster:
    name: home
  name: monize-app
  login: true
  superuser: false
  createdb: false
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: useraccount-monize-app