---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets
  namespace: monize
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets
  data:
  - secretKey: DATABASE_USER
    remoteRef:
      key: /database/monize
      property: username
  - secretKey: DATABASE_PASSWORD
    remoteRef:
      key: /database/monize
      property: password
  - secretKey: DATABASE_APP_USER
    remoteRef:
      key: /database/monize-app
      property: username
  - secretKey: DATABASE_APP_PASSWORD
    remoteRef:
      key: /database/monize-app
      property: password
  - secretKey: SMTP_USER
    remoteRef:
      key: /email/smtp2go
      property: username
  - secretKey: SMTP_PASSWORD
    remoteRef:
      key: /email/smtp2go
      property: password
  dataFrom:
  - extract:
      key: /monize

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: useraccount-monize
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: useraccount-monize
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: /database/monize
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: useraccount-monize-app
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: useraccount-monize-app
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: /database/monize-app
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
