---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-superuser
  namespace: cnpg
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: postgresql-superuser
  dataFrom:
  - extract:
      key: /postgresql/superuser
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-backblaze-postgresql
  namespace: cnpg
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: s3-backup-backblaze-postgresql
  dataFrom:
  - extract:
      key: /s3/backblaze
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-cloudflare-postgresql
  namespace: cnpg
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: s3-backup-cloudflare-postgresql
  dataFrom:
  - extract:
      key: /s3/cloudflare
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-oracle-postgresql
  namespace: cnpg
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: s3-backup-oracle-postgresql
  dataFrom:
  - extract:
      key: /s3/oracle
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-backup-nas01-postgresql
  namespace: cnpg
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: s3-backup-nas01-postgresql
  dataFrom:
  - extract:
      key: /s3/nas01
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: useraccount-grafana
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: useraccount-grafana
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: /database/grafana
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: useraccount-nextcloud
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: useraccount-nextcloud
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: /database/nextcloud
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
