fireflyiii:
  url: "http://firefly:80"
  vanityUrl: "https://firefly.laskonet.com"
config:
  existingSecret: firefly-secrets
  env:
    IGNORE_DUPLICATE_ERRORS: "false"
    TZ: "America/Toronto"
# securityContext:
#   capabilities:
#     drop:
#     - ALL
#   readOnlyRootFilesystem: false
  # runAsNonRoot: true
  # runAsUser: 1000    