alertmanager:
  config:
    global:
      slack_api_url_file: /etc/alertmanager/secrets/alertmanager-secrets/slack_webhook
      smtp_smarthost: 'mail.smtp2go.com:587'
      smtp_from: 'AlertManager Cloud<alertmanager-cloud@laskonet.com>'
      smtp_auth_username: 'SMTPSender@laskonet.com'
      smtp_auth_password_file: /etc/alertmanager/secrets/alertmanager-secrets/smtp_auth_password
      resolve_timeout: 5m
    route:
      group_wait: 5m
      group_interval: 10m
      repeat_interval: 4h
      receiver: 'null'
      routes:
      - receiver: 'slack-webhook'
        matchers:
        - severity = "warning"
        continue: false
      - receiver: 'ken-gmail'
        matchers:
        - severity = "warning"
        continue: false
    receivers:
    - name: 'null'
    - name: ken-gmail
      email_configs:
      - to: ken.lasko@gmail.com
    - name: slack-webhook
      slack_configs:
      - channel: cloud-alerts
        send_resolved: true
  alertmanagerSpec:
    externalUrl: 'https://cloud-alertmanager-omni.omni.laskonet.com'
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
  service:
    annotations:
      omni-kube-service-exposer.sidero.dev/prefix: cloud-alertmanager

grafana:
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: local-path
    accessModes: ["ReadWriteOnce"]
  service:
    annotations:
      omni-kube-service-exposer.sidero.dev/prefix: cloud-grafana

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 20Gi
  service:
    annotations:
      omni-kube-service-exposer.sidero.dev/prefix: cloud-prometheus