---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nectar-labs
  namespace: nectar-labs
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: nectar-labs
  data:
    - secretKey: COOKIE_SECRET
      remoteRef:
        key: /monize
        property: JWT_SECRET
