apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nectar-labs
resources:
  - namespace.yaml
  - external-secret.yaml
  - redis.yaml
  - auth.yaml
  - shell.yaml
  # - example-plugin.yaml
  - httproute.yaml
