---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-creds
  namespace: adguard
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: adguard-creds
  dataFrom:
  - extract:
      key: /adguard


---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-logcentral-secrets
  namespace: adguard
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: adguard-logcentral-secrets
  dataFrom:
  - extract:
      key: /adguard