featureGates: "ExperimentalGatewayAPISupport=true"
installCRDs: true
extraArgs:
- --dns01-recursive-nameservers-only
- --dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53
livenessProbe:
  enabled: true
prometheus:
  enabled: false
resources:
  requests:
    cpu: 1m
    memory: 22Mi
  limits:
    # cpu: 15m
    memory: 50Mi
extraEnv:
- name: TZ
  value: "America/Toronto"