---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets-sonarr
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets-sonarr
  dataFrom:
  - extract:
      key: /sonarr

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: useraccount-sonarr
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: useraccount-sonarr
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: /database/sonarr
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
