---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: env-secrets-tracearr
  namespace: media
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: env-secrets-tracearr
    template:
      engineVersion: v2
      data:
        JWT_SECRET: "{{ .jwtSecret }}"
        COOKIE_SECRET: "{{ .cookieSecret }}"
        DB_PASSWORD: "{{ .dbPassword }}"
        REDIS_URL: "redis://:{{ .redisPassword }}@redis-service.redis.svc.cluster.local:6379/1"
  data:
  - secretKey: jwtSecret
    remoteRef:
      key: /tracearr
      property: JWT_SECRET
  - secretKey: cookieSecret
    remoteRef:
      key: /tracearr
      property: COOKIE_SECRET
  - secretKey: dbPassword
    remoteRef:
      key: /database/tracearr
      property: password
  - secretKey: redisPassword
    remoteRef:
      key: /redis
      property: RI_REDIS_PASSWORD

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: useraccount-tracearr
  namespace: cnpg
  labels:
    cnpg.io/reload: "true"
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless
    kind: ClusterSecretStore
  target:
    name: useraccount-tracearr
    template:
      type: kubernetes.io/basic-auth
  dataFrom:
  - extract:
      key: /database/tracearr
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
